### ISSUE TITLE
Unable to resolve class RegionComparator, BAMIndexer

### ISSUE THREAD

**Issue by TMiguelT** [ssadedin/groovy-ngs-utils#2]
I get the following error when trying to compile groovy-ngs-utils using the commands listed in the readme:

```
:compileGroovy
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
startup failed:
/home/michael/Programming/groovy-ngs-utils/src/main/groovy/SAM.groovy: 1148: unable to resolve class BAMIndexer 
 @ line 1148, column 20.
           BAMIndexer indexer = new BAMIndexer(outputFile, reader.getFileHeader());
                      ^

/home/michael/Programming/groovy-ngs-utils/src/main/groovy/SAM.groovy: 1148: unable to resolve class BAMIndexer 
 @ line 1148, column 30.
           BAMIndexer indexer = new BAMIndexer(outputFile, reader.getFileHeader());
                                ^

/home/michael/Programming/groovy-ngs-utils/src/main/groovy/Regions.groovy: 685: unable to resolve class RegionComparator 
 @ line 685, column 43.
   regionsToSave = this.toSorted(new Region
                                 ^

3 errors

:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.077 secs
```

Perhaps the RegionComparator and BAMIndexer classes are not included as dependencies? The use of the RegionComparator class seems to have been introduced in 3240b14

**Comment by ssadedin** [comment]
Sorry about that - have done a general cleanup and fixed this problem as well. Should build cleanly now.
